# Generated by Django 2.0.2 on 2024-04-23 01:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240422_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 1, 29, 21, 465156, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
