# Generated by Django 5.0.2 on 2024-04-27 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 19, 30, 45, 750431, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicacion'),
        ),
    ]
